version: 0.20150918.{build}
image: Visual Studio 2017
configuration: Debug-CI
platform: Any CPU
shallow_clone: true
clone_folder: c:\Cosmos

init:
- cmd: |
    git clone https://github.com/CosmosOS/IL2CPU.git c:\IL2CPU --depth 1

build_script:
- cmd: |
    rem %APPVEYOR_BUILD_FOLDER%

    msbuild Build.sln /t:Restore;Build /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    dotnet publish ..\IL2CPU\source\IL2CPU -r win7-x86 -o "c:\CosmosRun\Build\IL2CPU\"

    xcopy /Y "Build\syslinux\*.*" "c:\CosmosRun\Build\ISO\"
    xcopy /Y /S "Build\VMware\*" "c:\CosmosRun\Build\VMware\"
    xcopy /Y /S "Build\Tools" "c:\CosmosRun\Build\Tools\"
    xcopy /Y "..\IL2CPU\source\Cosmos.Core.DebugStub\*.xs" "c:\CosmosRun\XSharp\DebugStub\"
    xcopy /Y /S "Resources\Bochs\*.*" "%ProgramFiles(x86)%\Bochs-2.6.8\"

    reg add HKLM\SOFTWARE\WOW6432Node\Cosmos /v UserKit /d c:\CosmosRun\
    reg add HKCR\BochsConfigFile\shell\Run\command /ve /d "\"C:\Program Files (x86)\Bochs-2.6.8\Bochs.exe\" -q -f \"%1\""

#test: off
#  assemblies:
#  - Cosmos.Core.Memory.Test.dll
#  - DebugCompiler.dll
#  - Cosmos.TestRunner.UnitTest.dll

test_script:
- cmd: dotnet test Tests\Cosmos.TestRunner.UnitTest\Cosmos.TestRunner.UnitTest.csproj --logger "trx;LogFileName=c:\Cosmos\TestResult.xml"

on_finish:
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", "c:\Cosmos\TestResult.xml")

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/d5c57ffb9a04b1b180be
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

matrix:
  fast_finish: true

artifacts:
  - path: 'artifacts\Debug\nupkg\*.nupkg'
  - path: 'artifacts\Debug\VSIX\*.vsix'
  - path: 'TestResult.xml'
